### ISSUE TITLE
嗨，我也在尝试写个rpc轮子，目前遇到了一些问题，可以一起探讨吗

### ISSUE THREAD

**Issue by sunl888** [captainbing/trible-rpc#1]
我目前遇到的问题是当我想把我的rpc封装成springbootstarter时发现我的配置文件模块设计的有大问题，不知道怎么在starter中优雅的设置我的各种配置项，然后再根据这些配置项进行加载对应的扩展

**Comment by sunl888** [comment]
这是我的项目地址，您有空帮我看看吗，https://github.com/sunl888/rocket

**Comment by bing-zhong** [comment]
可以查看一下最新提交的代码，希望能给你提供帮助

**Comment by sunl888** [comment]
> 可以查看一下最新提交的代码，希望能给你提供帮助

好嘞，非常感谢哈，晚上回去看看您的代码学习一下
